### ISSUE TITLE
Old Backups are not being deleted

### ISSUE THREAD

**Issue by N1Ran** [sirhamsteralot/TorchBackupSystem#3]
Version: 0.7.1.51

Error being thrown by the plugin

13:04:11.4603 [ERROR]  Backup: Exception when deleting old backup. Please check the backup folder and delete old files as needed.
    at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at TorchBackupSystem.BackupTimer.RunBackup(Object state)
13:04:11.4603 [INFO]   Backup: Configuration Saved.
13:04:11.4935 [ERROR]  Backup: Exception when deleting old backup. Please check the backup folder and delete old files as needed.
    at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at TorchBackupSystem.BackupTimer.RunBackup(Object state)
13:04:11.4935 [INFO]   Backup: Configuration Saved.
13:04:11.4935 [ERROR]  Backup: Exception when deleting old backup. Please check the backup folder and delete old files as needed.
    at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at TorchBackupSystem.BackupTimer.RunBackup(Object state)

**Comment by N1Ran** [comment]
I have a fix for this if you're interested

**Comment by MaceUD** [comment]
Hey, 

I am still encountering this issue myself. I set up a 4 maximum backup and I get a lot more ...

Thank you for considering the issue

![1](https://user-images.githubusercontent.com/64008256/87659823-63984c00-c75e-11ea-8d40-280eb7bdfef5.PNG)
![2](https://user-images.githubusercontent.com/64008256/87659924-89bdec00-c75e-11ea-89bf-30fb38182ced.PNG)

**Comment by CaptainGuppy** [comment]
@N1Ran I see the same problems as aforementioned and would like a fix, please. Thanks!
