### ISSUE TITLE
Rare null object crash during init

### ISSUE THREAD

**Issue by SplenectomY** [sirhamsteralot/TorchBackupSystem#4]
Only happened once and then the server started seemingly normally. Can probably be prevented though.

Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
   at TorchBackupSystem.BackupTimer.OnTimerTrigger(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
System.NullReferenceException: Object reference not set to an instance of an object.
   at TorchBackupSystem.BackupTimer.OnTimerTrigger(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

**Comment by MisterRee** [comment]
Did we ever discover what causes this issue? Our server crashed with this error...
```
16:11:11.1140 [FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
   at TorchBackupSystem.BackupTimer.OnTimerTrigger(Object state) in D:\VisualStudio\Projects\TorchBackupSystem\TorchBackupSystem\BackupTimer.cs:line 75
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.NullReferenceException: Object reference not set to an instance of an object.
   at TorchBackupSystem.BackupTimer.OnTimerTrigger(Object state) in D:\VisualStudio\Projects\TorchBackupSystem\TorchBackupSystem\BackupTimer.cs:line 75
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
